[project]
name = 'Collective-Unconscious-Mapping-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ai-analysis]
path = 'contracts/ai-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.collective-token]
path = 'contracts/collective-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-storage]
path = 'contracts/data-storage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
